name: Prevent Supabase Inactivity

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
    - cron: '0 0 * * 0'  # Runs at midnight every Sunday


jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API request to Supabase
        env:
          SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
            curl -sS "${SUPABASE_URL}/rest/v1/projects?select=*&order=created_at.desc" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -H "Accept: application/json"